/*
 * Filename: swc_errorhandler.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component
 * name: swc_errorHandler
 * shortname: errorHandler
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_errorhandler.h"



/* USER CODE START SWC_ERRORHANDLER_INCLUDE */

/* USER CODE END SWC_ERRORHANDLER_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_ERRORHANDLER_USERDEFINITIONS */

/* USER CODE END SWC_ERRORHANDLER_USERDEFINITIONS */



/*
 * component: swc_errorHandler
 * cycletime: 0
 * description: Runnable
 * events: ev_ev_errorHandler
 * name: ERRORHANDLER_errorHandler_run
 * shortname: errorHandler
 * signalIN: 
 * signalOUT: 
 * task: tsk_errorHandling
 */
void ERRORHANDLER_errorHandler_run(RTE_event ev){
	
	/* USER CODE START ERRORHANDLER_errorHandler_run */

    /* USER CODE END ERRORHANDLER_errorHandler_run */
}

/* USER CODE START SWC_ERRORHANDLER_FUNCTIONS */

/* USER CODE END SWC_ERRORHANDLER_FUNCTIONS */

