
/*
 * Filename: swc_system.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Software component
 */

#ifndef _H_DEFINE_SWC_SYSTEM
#define _H_DEFINE_SWC_SYSTEM

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_SYSTEM_INCLUDES */

/* USER CODE END SWC_SYSTEM_INCLUDES */



/* USER CODE START SWC_SYSTEM_USERDEFINITIONS */

/* USER CODE END SWC_SYSTEM_USERDEFINITIONS */


/*
 * component: swc_system
 * cycletime: 1
 * description: Runnable
 * events: 
 * name: SYSTEM_system_run
 * shortname: system
 * signalIN: 
 * signalOUT: 
 * task: tsk_system
 */
void SYSTEM_system_run(RTE_event ev);


#endif