/*
 * Filename: swc_output.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: engine and brakelights
 * name: swc_output
 * shortname: output
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_output.h"



/* USER CODE START SWC_OUTPUT_INCLUDE */
#include "watchdog.h"
#include "error.h"

/* USER CODE END SWC_OUTPUT_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_OUTPUT_USERDEFINITIONS */

/* USER CODE END SWC_OUTPUT_USERDEFINITIONS */



/*
 * component: swc_output
 * cycletime: 100
 * description: Sets Green LED according to Engine Speed
 * events: 
 * name: OUTPUT_setEngine_run
 * shortname: setEngine
 * signalIN: so_speed
 * signalOUT: so_engine
 * task: tsk_io
 */
void OUTPUT_setEngine_run(RTE_event ev){
	
	/* USER CODE START OUTPUT_setEngine_run */
        WD_Alive(WATCHDOG_RUN_SETENGINE);
    if (ERROR_isRunnableActive(ERROR_SET_ENGINE) == FALSE){
        return;
    
    }

    if (RTE_SC_SPEED_getStatus(&SO_SPEED_signal) != RTE_SIGNALSTATUS_VALID) {
        return;
    }
    
    SC_SPEED_data_t speed = SC_SPEED_INIT_DATA;
  
    RTE_SC_SPEED_getThreadSafe(&SO_SPEED_signal, &speed);
    
    SC_ENGINE_data_t engine = SC_ENGINE_INIT_DATA;
    
    if (RTE_SC_SPEED_getAge(&SO_SPEED_signal) < 50){
        engine.m_engineValue = speed.m_speedValue;
    } else {
        engine.m_engineValue = 0;
    }
    
    RTE_SC_ENGINE_set(&SO_ENGINE_signal, engine);
    RTE_SC_ENGINE_pushPort(&SO_ENGINE_signal);
    


    /* USER CODE END OUTPUT_setEngine_run */
}

/*
 * component: swc_output
 * cycletime: 0
 * description: Sets LED according to brake condition
 * events: ev_speed_onData
 * name: OUTPUT_setBrakeLight_run
 * shortname: setBrakeLight
 * signalIN: so_speed
 * signalOUT: so_brakelight
 * task: tsk_io
 */
void OUTPUT_setBrakeLight_run(RTE_event ev){
	
	/* USER CODE START OUTPUT_setBrakeLight_run */
        WD_Alive(WATCHDOG_RUN_SETBRAKELIGHT);
    if (ERROR_isRunnableActive(ERROR_SET_BRAKELIGHT) == FALSE){
        return;
    
    }

    if (RTE_SC_SPEED_getStatus(&SO_SPEED_signal) != RTE_SIGNALSTATUS_VALID) {
        return;
    }
    
    SC_SPEED_data_t speed = SC_SPEED_INIT_DATA;
  
    RTE_SC_SPEED_getThreadSafe(&SO_SPEED_signal, &speed);
    

    SC_BRAKELIGHT_data_t brake = SC_BRAKELIGHT_INIT_DATA;
    
    if (speed.m_speedValue <= 0){
        brake.m_brakeValue = TRUE;
    }
    
    RTE_SC_BRAKELIGHT_set(&SO_BRAKELIGHT_signal, brake);
    
    RC_t error = RTE_SC_BRAKELIGHT_pushPort(&SO_BRAKELIGHT_signal);


    /* USER CODE END OUTPUT_setBrakeLight_run */
}

/* USER CODE START SWC_OUTPUT_FUNCTIONS */

/* USER CODE END SWC_OUTPUT_FUNCTIONS */

