/*
 * Filename: swc_joystick.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Input
 * name: swc_joystick
 * shortname: joystick
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_joystick.h"



/* USER CODE START SWC_JOYSTICK_INCLUDE */

/* USER CODE END SWC_JOYSTICK_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_JOYSTICK_USERDEFINITIONS */

/* USER CODE END SWC_JOYSTICK_USERDEFINITIONS */



/*
 * component: swc_joystick
 * cycletime: 10
 * description: takes input from joysticl
 * events: 
 * name: JOYSTICK_readJoystick_run
 * shortname: readJoystick
 * signalIN: 
 * signalOUT: so_joystick
 * task: tsk_control
 */
void JOYSTICK_readJoystick_run(RTE_event ev){
	
	/* USER CODE START JOYSTICK_readJoystick_run */

    /* USER CODE END JOYSTICK_readJoystick_run */
}

/* USER CODE START SWC_JOYSTICK_FUNCTIONS */

/* USER CODE END SWC_JOYSTICK_FUNCTIONS */

