/*
 * Filename: swc_input.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Input
 * name: swc_input
 * shortname: input
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_input.h"



/* USER CODE START SWC_INPUT_INCLUDE */

/* USER CODE END SWC_INPUT_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_INPUT_USERDEFINITIONS */

/* USER CODE END SWC_INPUT_USERDEFINITIONS */



/*
 * component: swc_input
 * cycletime: 10
 * description: takes input from joystick
 * events: 
 * name: INPUT_readJoystick_run
 * shortname: readJoystick
 * signalIN: 
 * signalOUT: so_joystick
 * task: tsk_input
 */
void INPUT_readJoystick_run(RTE_event ev){
	
	/* USER CODE START INPUT_readJoystick_run */

    //UART_Logs_PutString("Reading Joystick value, update so_joystick\n");
    RTE_SC_JOYSTICK_pullPort(&SO_JOYSTICK_signal);
    UART_Logs_PutChar(SO_JOYSTICK_signal.value.m_joystickValueX);
    //UART_Logs_PutChar(SO_JOYSTICK_signal.value.m_joystickValueY);
    

    /* USER CODE END INPUT_readJoystick_run */
}

/* USER CODE START SWC_INPUT_FUNCTIONS */

/* USER CODE END SWC_INPUT_FUNCTIONS */

