/*
 * Filename: swc_system.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component
 * name: swc_system
 * shortname: system
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_system.h"



/* USER CODE START SWC_SYSTEM_INCLUDE */

#include "sc_speed.h"
#include "watchdog.h"

/* USER CODE END SWC_SYSTEM_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_SYSTEM_USERDEFINITIONS */

#define TEST_AGE 0

/* USER CODE END SWC_SYSTEM_USERDEFINITIONS */



/*
 * component: swc_system
 * cycletime: 1
 * description: Runnable
 * events: 
 * name: SYSTEM_system_run
 * shortname: system
 * signalIN: 
 * signalOUT: 
 * task: tsk_system
 */
void SYSTEM_system_run(RTE_event ev){
	
	/* USER CODE START SYSTEM_system_run */

    
    #if TEST_AGE == 0
        RTE_timertick_sp_common_tick(1);
    #endif
    
    #if TEST_AGE == 1
        RTE_timertick_sp_common_tick(500);
    #endif
    WD_Alive(WATCHDOG_RUN_SYSTEM);
    
    
    /* USER CODE END SYSTEM_system_run */
}

/* USER CODE START SWC_SYSTEM_FUNCTIONS */

/* USER CODE END SWC_SYSTEM_FUNCTIONS */

