/*
 * Filename: swc_control.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: calculation control
 * name: swc_control
 * shortname: control
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_control.h"




/* USER CODE START SWC_CONTROL_INCLUDE */
#include "watchdog.h"
#include "error.h"

/* USER CODE END SWC_CONTROL_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_CONTROL_USERDEFINITIONS */

/* USER CODE END SWC_CONTROL_USERDEFINITIONS */



/*
 * component: swc_control
 * cycletime: 0
 * description: Takes in Joystick data and updates Speed
 * events: ev_joystick_onData
 * name: CONTROL_calcControl_run
 * shortname: calcControl
 * signalIN: so_joystick
 * signalOUT: so_speed
 * task: tsk_control
 */
void CONTROL_calcControl_run(RTE_event ev){
	
	/* USER CODE START CONTROL_calcControl_run */
    WD_Alive(WATCHDOG_RUN_CALCCONTROL);
    if (ERROR_isRunnableActive(ERROR_CONTROL) == FALSE){
        return;
    
    }
        
    if (RTE_SC_JOYSTICK_getStatus(&SO_JOYSTICK_signal) != RTE_SIGNALSTATUS_VALID) {
        return;
    }
    
    SC_JOYSTICK_data_t joystickData = SC_JOYSTICK_INIT_DATA;

    RTE_SC_JOYSTICK_getThreadSafe(&SO_JOYSTICK_signal, &joystickData);
    SC_SPEED_data_t speed = SC_SPEED_INIT_DATA;
    
    if (joystickData.m_joystickValue > 0){
        speed.m_speedValue = 2 * joystickData.m_joystickValue;
    }

    RTE_SC_SPEED_set(&SO_SPEED_signal, speed);


    /* USER CODE END CONTROL_calcControl_run */
    
    
}

/* USER CODE START SWC_CONTROL_FUNCTIONS */

/* USER CODE END SWC_CONTROL_FUNCTIONS */

