/*
 * Filename: swc_control.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: calculation control
 * name: swc_control
 * shortname: control
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_control.h"



/* USER CODE START SWC_CONTROL_INCLUDE */

/* USER CODE END SWC_CONTROL_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_CONTROL_USERDEFINITIONS */

/* USER CODE END SWC_CONTROL_USERDEFINITIONS */



/*
 * component: swc_control
 * cycletime: 0
 * description: Takes in Joystick data and updates Speed
 * events: ev_joystick_onData
 * name: CONTROL_calcControl_run
 * shortname: calcControl
 * signalIN: so_joystick
 * signalOUT: so_speed
 * task: tsk_control
 */
void CONTROL_calcControl_run(RTE_event ev){
	
	/* USER CODE START CONTROL_calcControl_run */
//    UART_Logs_PutString("In Control swc\n");
    SC_JOYSTICK_data_t joystickData = RTE_SC_JOYSTICK_get(&SO_JOYSTICK_signal);
    SC_SPEED_data_t speed = SC_SPEED_INIT_DATA;
    
    if (joystickData.m_joystickValue > 0){
        speed.m_speedValue = 2 * joystickData.m_joystickValue;
    }

    //UART_Logs_PutChar(joystickData.m_joystickValueX);
    RTE_SC_SPEED_set(&SO_SPEED_signal, speed);
//    UART_Logs_PutChar(SO_SPEED_signal.value.m_speedValue);
//    UART_Logs_PutString("\n"); 
    
//    SC_SPEED_data_t data = {60};
//    RC_t error = RTE_SC_SPEED_set(&SO_SPEED_signal, data);
//    UART_Logs_PutString("In control\n");

    /* USER CODE END CONTROL_calcControl_run */
}


/* USER CODE START SWC_CONTROL_FUNCTIONS */

/* USER CODE END SWC_CONTROL_FUNCTIONS */

