/*
 * Filename: tsk_logging.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Task to log data on UART/TFT
 * events: ev_joystick_onData
 * mode: Event
 * name: tsk_logging
 * shortname: logging
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: ev_joystick_onData
 * timertickperiod: 1
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "tsk_logging.h"



/* USER CODE START TSK_LOGGING_INCLUDE */

/* USER CODE END TSK_LOGGING_INCLUDE */

#include "swc_logging.h"



/* USER CODE START TSK_LOGGING_USERDEFINITIONS */

/* USER CODE END TSK_LOGGING_USERDEFINITIONS */

/*******************************************************************************
 * Runnable Tables from Activation Engine
 *******************************************************************************/

/* Event Table */
const RTE_eventTable_t RTE_eventActivationTable_tsk_logging[] = {
    { LOGGING_logging_run, ev_joystick_onData },  //Runnable
}; 
const uint16_t RTE_eventActivation_tsk_logging_size = sizeof (RTE_eventActivationTable_tsk_logging) / sizeof(RTE_eventTable_t);

/*******************************************************************************
 * Task Body
 *******************************************************************************/


/*
 * description: Task to log data on UART/TFT
 * events: ev_joystick_onData
 * mode: Event
 * name: tsk_logging
 * shortname: logging
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: ev_joystick_onData
 * timertickperiod: 1
 */
TASK(tsk_logging)
{
    EventMaskType ev = 0;
    
	/* USER CODE START TSK_LOGGING_INIT */
    


	/* USER CODE END TSK_LOGGING_INIT */
	
    while(1)
    {
        //Wait, read and clear the event
        WaitEvent(ev_joystick_onData);
        GetEvent(tsk_logging,&ev);
        ClearEvent(ev);
		
		/* USER CODE START TSK_LOGGING_TASKBOBY_PRE */
        SetRelAlarm(alrm_error_logging, 80, 0);
		/* USER CODE END TSK_LOGGING_TASKBODY_PRE */
    

        //Process Event table on event
        RTE_ProcessEventTable(RTE_eventActivationTable_tsk_logging, RTE_eventActivation_tsk_logging_size, ev);
		
		/* USER CODE START TSK_LOGGING_TASKBODY_POST */

        CancelAlarm(alrm_error_logging);
        
		/* USER CODE END TSK_LOGGING_TASKBODY_POST */

        
    }
	
	//Just in Case
	TerminateTask();
}


/*******************************************************************************
 * Interrupt Service Routines
 *******************************************************************************/

/* USER CODE START TSK_LOGGING_ISR */

/* USER CODE END TSK_LOGGING_ISR */

