/*
 * Filename: tsk_system.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Task managing the system
 * events: 
 * mode: Cyclic
 * name: tsk_system
 * shortname: system
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: 0
 * timertickperiod: 1
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "tsk_system.h"



/* USER CODE START TSK_SYSTEM_INCLUDE */

/* USER CODE END TSK_SYSTEM_INCLUDE */

#include "swc_system.h"



/* USER CODE START TSK_SYSTEM_USERDEFINITIONS */

/* USER CODE END TSK_SYSTEM_USERDEFINITIONS */

/*******************************************************************************
 * Runnable Tables from Activation Engine
 *******************************************************************************/

/* Cyclic Table */

const RTE_cyclicTable_t RTE_cyclicActivationTable_tsk_system[] = {
	{ SYSTEM_system_run, 5 },	//Runnable
};
const uint16_t RTE_cyclicActivation_tsk_system_size = sizeof (RTE_cyclicActivationTable_tsk_system) / sizeof(RTE_cyclicTable_t); 


/*******************************************************************************
 * Task Body
 *******************************************************************************/


/*
 * description: Task managing the system
 * events: 
 * mode: Cyclic
 * name: tsk_system
 * shortname: system
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: 0
 * timertickperiod: 5
 */
TASK(tsk_system)
{
	/* ticktime of the task */
	static uint32_t ticktime = 0;

	/* USER CODE START TSK_SYSTEM_TASKBOBY_PRE */

	/* USER CODE END TSK_SYSTEM_TASKBODY_PRE */
    
    //Process all cyclic runnables which are due
    RTE_ProcessCyclicTable(RTE_cyclicActivationTable_tsk_system, RTE_cyclicActivation_tsk_system_size, ticktime);
	
	/* USER CODE START TSK_SYSTEM_TASKBODY_POST */

	/* USER CODE END TSK_SYSTEM_TASKBODY_POST */

	ticktime += 5;
	if (ticktime > 0xFFFFFF00) ticktime = 0;
	
	TerminateTask();
    
}


/*******************************************************************************
 * Interrupt Service Routines
 *******************************************************************************/

/* USER CODE START TSK_SYSTEM_ISR */

/* USER CODE END TSK_SYSTEM_ISR */

