
/*
 * Filename: tsk_logging.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Task to log data on UART/TFT
 */

#ifndef _H_DEFINE_TSK_LOGGING
#define _H_DEFINE_TSK_LOGGING

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START TSK_LOGGING_INCLUDES */

/* USER CODE END TSK_LOGGING_INCLUDES */



/*
 * description: Task to log data on UART/TFT
 * events: ev_joystick_onData
 * mode: Event
 * name: tsk_logging
 * shortname: logging
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: ev_joystick_onData
 * timertickperiod: 1
 */
DeclareTask(tsk_logging);

/* USER CODE START TSK_LOGGING_TASKUSERFUNCTION */

/* USER CODE END TSK_LOGGING_TASKUSERFUNCTION */


#endif