
/*
 * Filename: tsk_errorhandler.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Task acting on error conditions
 */

#ifndef _H_DEFINE_TSK_ERRORHANDLER
#define _H_DEFINE_TSK_ERRORHANDLER

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START TSK_ERRORHANDLER_INCLUDES */
#include "error.h"

/* USER CODE END TSK_ERRORHANDLER_INCLUDES */



/*
 * description: Task doing work
 * events: ev_error
 * mode: Event
 * name: tsk_errorHandler
 * shortname: errorHandler
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: 0
 * timertickperiod: 1
 */
DeclareTask(tsk_errorhandler);

/* USER CODE START TSK_ERRORHANDLER_TASKUSERFUNCTION */



/* USER CODE END TSK_ERRORHANDLER_TASKUSERFUNCTION */


#endif