/*
 * Filename: sc_brakelight_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Signal for brake
 * name: sc_brakelight
 * shortname: brakelight
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_brakelight_type.h"



/* USER CODE START SC_BRAKELIGHT_INCLUDE */
#include "led.h"

/* USER CODE END SC_BRAKELIGHT_INCLUDE */




/* USER CODE START SC_BRAKELIGHT_USERDEFINITIONS */

/* USER CODE END SC_BRAKELIGHT_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_BRAKELIGHT signal  ****************
 *****************************************************************************************/
 
 
/**
 * Default OUT driver API
 */
inline RC_t SC_BRAKELIGHT_driverOut(const SC_BRAKELIGHT_data_t  *const data)
{
	/* USER CODE START driverOutSC_BRAKELIGHT */
    
	//Scale application data to drive format
    
    LED_ONOFF_t LEDvalue = data -> m_brakeValue;

	//Write scaled data to driver
    
    return LED_Set(LED_RED, LEDvalue);

	/* USER CODE END driverOutSC_BRAKELIGHT */
}



