
/*
 * Filename: sc_brakelight_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Signal for brake
 */

#ifndef _H_DEFINE_SC_BRAKELIGHT_TYPE
#define _H_DEFINE_SC_BRAKELIGHT_TYPE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SC_BRAKELIGHT_INCLUDES */

/* USER CODE END SC_BRAKELIGHT_INCLUDES */



/**********************************************************************
 *       Type Definition for SC_BRAKELIGHT signal    
 **********************************************************************/

/* USER CODE START SC_BRAKELIGHT_USERDEFINITIONS */

/* USER CODE END SC_BRAKELIGHT_USERDEFINITIONS */

typedef 
/* USER CODE START SC_BRAKELIGHT_SIGNALDATADEFINITION */
struct
{
	#error "Provide your data structure"
} 
/* USER CODE END SC_BRAKELIGHT_SIGNALDATADEFINITION */
SC_BRAKELIGHT_data_t;

/* USER CODE START InitSC_BRAKELIGHT */
#error "Provide a sensible init value"
#define SC_BRAKELIGHT_INIT_DATA ((SC_BRAKELIGHT_data_t){})
/* USER CODE END InitSC_BRAKELIGHT */





/* USER CODE START SC_BRAKELIGHT_USERFUNCTIONS */

/* USER CODE END SC_BRAKELIGHT_USERFUNCTIONS */


#endif