/*
 * Filename: sc_logging_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: signal for HMI devices
 * name: sc_logging
 * shortname: logging
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_logging_type.h"



/* USER CODE START SC_LOGGING_INCLUDE */
#include "tft.h"

/* USER CODE END SC_LOGGING_INCLUDE */




/* USER CODE START SC_LOGGING_USERDEFINITIONS */

/* USER CODE END SC_LOGGING_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_LOGGING signal  ****************
 *****************************************************************************************/
 
 
/**
 * Default OUT driver API
 */
inline RC_t SC_LOGGING_driverOut(const SC_LOGGING_data_t  *const data)
{
	/* USER CODE START driverOutSC_LOGGING */
    
    static boolean_t firstUse = 1;
    
    if (firstUse == 1){
        UART_Logs_PutString(data->m_loggingEntity);
        
        TFT_setCursor(0, 30);
        TFT_print(data->m_loggingEntity);
        firstUse = 0;
    } 
    
    if (data ->loggingDisabled == 1){
        TFT_setCursor(0, 0);
        TFT_clearScreen();
        TFT_print("Logging Disabled to enhance performance");
        return RC_SUCCESS;
    }
    
    UART_Logs_PutString(data->m_loggingEntity);
    UART_Logs_PutString(": ");
    UART_Logs_PutString(data->loggingValue);
    UART_Logs_PutString("\n");
    
    TFT_setCursor(0, 40);
    TFT_print(data->loggingValue);
    

    return RC_SUCCESS;
    
	//Write scaled data to driver

	/* USER CODE END driverOutSC_LOGGING */
}



