
/*
 * Filename: sp_common.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: The common global signal pool, all signals will be stored here
 */

#ifndef _H_DEFINE_SP_COMMON
#define _H_DEFINE_SP_COMMON

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SP_COMMON_INCLUDES */

/* USER CODE END SP_COMMON_INCLUDES */



#include "sc_speed.h"
#include "sc_speed.h"
#include "sc_speed.h"
#include "sc_brakelight.h"



/*
 * description: Joystick position (x, y)
 * indriver: default
 * name: so_joystick
 * onDataError: 0
 * onDataUpdate: ev_joystick_onData
 * outdriver: 0
 * resource: None
 * shortname: joystick
 * signalclass: sc_speed
 * signalpool: sp_common
 */
extern SC_SPEED_t SO_JOYSTICK_signal;


/*
 * description: Speed of the car 
 * indriver: default
 * name: so_speed
 * onDataError: 0
 * onDataUpdate: ev_speed_onData
 * outdriver: 0
 * resource: None
 * shortname: speed
 * signalclass: sc_speed
 * signalpool: sp_common
 */
extern SC_SPEED_t SO_SPEED_signal;


/*
 * description: Engine speed
 * indriver: 0
 * name: so_engine
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: 0
 * resource: None
 * shortname: engine
 * signalclass: sc_speed
 * signalpool: sp_common
 */
extern SC_SPEED_t SO_ENGINE_signal;


/*
 * description: A Signal for brakelights
 * indriver: 0
 * name: so_brakelight
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: 0
 * resource: None
 * shortname: brakelight
 * signalclass: sc_brakelight
 * signalpool: sp_common
 */
extern SC_BRAKELIGHT_t SO_BRAKELIGHT_signal;



/*
 * Increments the age of the signals in this pool 
 */
void RTE_timertick_sp_common_tick(uint32_t tick);

/*
 * Reset all signals in this pool
 */
void RTE_reset_sp_common();

#endif