/*
 * Filename: sc_logging_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: signal for HMI devices
 * name: sc_logging
 * shortname: logging
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_logging_type.h"



/* USER CODE START SC_LOGGING_INCLUDE */

/* USER CODE END SC_LOGGING_INCLUDE */




/* USER CODE START SC_LOGGING_USERDEFINITIONS */

/* USER CODE END SC_LOGGING_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_LOGGING signal  ****************
 *****************************************************************************************/
 
 
/**
 * Default OUT driver API
 */
inline RC_t SC_LOGGING_driverOut(const SC_LOGGING_data_t  *const data)
{
	/* USER CODE START driverOutSC_LOGGING */
#error "Add your code here"

	//Scale application data to drive format

	//Write scaled data to driver

	return RC_SUCCESS;
	/* USER CODE END driverOutSC_LOGGING */
}



